export default {
  url: {
    login: "/",
    logout: "/logout",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    changePassword: "/change-password",
    register: "/register",
    dashboard: "/dashboard",
    payrollDashboard: "/dashboard/payroll",
    chatBot: "/bot",
    acknowledgeConfig: "/acknowledge-config",
    language: "/language",

    epms: "/epms",
    epmsconfig: "/epms/config",
    addKRA: "/epms/addKRA",
    mapKRA: "/epms/mapKRA",
    userRoleMap: "/epms/userRoleMap",
    addFixedQues: "/epms/addFixedQues",

    getAuthenticationFormComplete: "/getAuthenticationFormComplete",

    onboardEditBasic: "/onboard/basic",

    employeeList: "/employee/list",
    empSalarySlip: "/employee/salary-slip",
    addEmployeeMaster: "/employee/master",
    employeeDetail: "/employee/detail/:id",
    editEmployeeBasic: "/employee/basic/:id",
    editEmployeeMaster: "/employee/master/:id",
    employeeBulkUpload: "/employee/bulk-upload",
    editEmployeeAddress: "/employee/address/:id",
    editEmployeeEducation: "/employee/education/:id",
    editEmployeeExperience: "/employee/experience/:id",
    editTrainingExperience: "/employee/training-experience/:id",
    departmentalEnquiry: "/employee/departmental-enquiry/:id",
    editEmployeeBank: "/employee/bank/:id",
    editEmployeeDocument: "/employee/document/:id",
    editEmployeeFamily: "/employee/family/:id",
    editEmployeeWork: "/employee/work/:id",
    editEmployeeSalary: "/employee/salary/:id",
    editEmployeeNomination: "/employee/nomination/:id",
    editEmployeeLeaveBalance: "/employee/leave-balance/:id",
    editEmployeeProfilePicture: "/employee/profile-picture/:id",

    editEmployeeLifeInsurance: "/employee/declarations/:id",
    jobHistory: "/employee/job-history/:id",

    obEmployeeBasic: "/onboard/basic",
    obEmployeeAddress: "/onboard/address",
    obEmployeeEducation: "/onboard/education",
    obEmployeeExperience: "/onboard/experience",
    obEmployeeBank: "/onboard/bank",
    obEmployeeDocument: "/onboard/document",
    obEmployeeFamily: "/onboard/family",
    obEmployeeWork: "/onboard/work",
    obEmployeeSalary: "/onboard/salary",

    perquisites: {
      vuserInfo: "/perquisites/info",
      vallowance: "/perquisites/vehicle-allowance",
      vaddAllowance: "/perquisites/vehicle-allowance/add",
      vpendingAllowance: "/perquisites/pending-vehicle-allowance",
      vapproveAllowance: "/perquisites/approve-vehicle-allowance/:id",

      tadaAllowanceFile: "/tada-allowance/",
      tadaAllowance: "/perquisites/tada-allowance",
      tadaAddAllowance: "/perquisites/tada-allowance/add",
      tadaDetilAllowance: "/perquisites/tada-allowance/detail/:id",
      tadaPendingAllowance: "/perquisites/pending-tada-allowance",
      tadaApproveAllowance: "/perquisites/approve-tada-allowance/:id",
      tadaAllowanceRecommendation: "/perquisites/recommend-tada-allowance",
      tadaAllowanceRecommendationApprove:
        "/perquisites/recommend-tada-allowance/:id",

      newsPaperAllowance: "/perquisites/news-paper-allowance",
      newsPaperAddAllowance: "/perquisites/news-paper-allowance/add",
      newsPaperPendingAllowance: "/perquisites/pending-news-paper",
      newsPaperApproveAllowance: "/perquisites/approve-news-allowance/:id",

      briefCasePaperAllowance: "/perquisites/brief-case-allowance",
      briefCasePaperPendingAllowance: "/perquisites/pending-brief-case",
      briefCasePaperAddAllowance: "/perquisites/brief-case-allowance/add",
      briefCasePaperApproveAllowance: "/perquisites/approve-brief-case/:id",
      briefCasePaperAllowanceDetail:
        "/perquisites/brief-case-allowance/detail/:id",

      mobileAllowanceFile: "/mobile-allowance/",
      mobileAllowance: "/perquisites/mobile-allowance",
      mobileAddAllowance: "/perquisites/mobile-allowance/add",
      mobilePendingAllowance: "/perquisites/pending-mobile-allowance",
      mobileApproveAllowance: "/perquisites/approve-mobile-allowance/:id",

      entertainmentAllowanceFile: "/entertainment-allowance/",
      entertainmentAllowance: "/perquisites/entertainment-allowance",
      entertainmentAddAllowance: "/perquisites/entertainment-allowance/add",
      entertainmentPendingAllowance: "/perquisites/pending-entertainment",
      entertainmentApproveAllowance: "/perquisites/approve-entertainment/:id",

      uniformAndLiveriesAllowance: "/perquisites/uniform-liveries-allowance",
      uniformAndLiveriesAddAllowance:
        "/perquisites/uniform-liveries-allowance/add",
      uniformAndLiveriesPendingAllowance:
        "/perquisites/pending-uniform-liveries",
      uniformAndLiveriesApproveAllowance:
        "/perquisites/approve-uniform-liveries/:id",

      medicalAllowance: "/perquisites/medical-allowance",
      medicalAddAllowance: "/perquisites/medical-allowance/add",
      medicalDetilAllowance: "/perquisites/medical-allowance/detail/:id",
      medicalPendingAllowance: "/perquisites/pending-medical-allowance",
      medicalApproveAllowance: "/perquisites/approve-medical-allowance/:id",
    },
    payment: {
      salary: "/payment/salary",
      festival: "/payment/festival",
      vallowance: "/payment/vehicle-allowance",
      tadaAllowance: "/payment/tada-allowance",
      newsPaperAllowance: "/payment/news-paper-allowance",
      briefCasePaperAllowance: "/payment/brief-case-allowance",
      mobileAllowance: "/payment/mobile-allowance",
      entertainmentAllowance: "/payment/entertainment-allowance",
      uniformAndLiveriesAllowance: "/payment/uniform-liveries-allowance",
      medicalAllowance: "/payment/medical-allowance",
      updateTrans: "/payment/transaction",
    },
    reports: {
      employeeReports: "/reports/employeeReports",
      reportingManagerDetails: "/reports/reportingManagerDetails",
      employeeLeaveReports: "/reports/employee-leave-reports",
      employeeLeaveReportsAdmin: "/reports/employee-leave-reports/admin",
    },

    // addExperience: '/add/experience',
    // addFamily: '/add/family',
    // addEducation: '/add/education',

    // addEmployeeMaster: '/employee/add/profile',
    // addEmployeeBank: '/employee/add/bank-detail',
    // addEmployeeFamily: '/employee/add/family',
    // addEmployeeWork: '/employee/add/work-profile',
    // addEmployeeDocument: '/employee/add/document',
    // addEmployeeSalaryProfile: '/employee/add/salary-profile',
    // addEmployeeBasic: '/employee/add/basic',
    // addEmployeeAddress: '/employee/add/address',
    // addEmployeeEducation: '/employee/add/educational',
    // addEmployeeExp: '/employee/add/experience',
    // addEmployeeSalary: '/employee/add/salary',
    // addEmployeeCompensation: '/employee/add/compensation',
    // editEmployee: '/employee/:code',

    managerChange: "/manager-change",
    myCompensastion: "/my-compensastion",
    OASys: "/OASys",
    payroll: "/payroll",
    pms: "/pms",
    proxyMapping: "/proxy-mapping",
    recruitment: "/recruitment",
    report: "/report",
    shiftRoster: "/shift-roster",
    systemMoniter: "/system-moniter",
    userStatus: "/user-status",
    mountLogin: "/mount-login",
    lg: "/lg",
    geoConfigSetup: "/geo-config-setup",
    documentUpload: "/document-upload",
    attendance: "/attendance",
    attendanceReport: "/attendance-dashboard",
    attendanceHistory: "/attendance-history",
    employeeAttendance: "/attendance/:code",
    uploadAttendance: "/upload-attendance",

    holidayList: "/holiday",
    addHoliday: "/holiday/add",
    bulkUploadHolidays: "/holiday/bulk-upload",
    editHoliday: "/holiday/edit/:code",

    fasitvalAddList: "/fastival/list",
    fasitvalAddPendigList: "/fastival/pending-approvals",
    fasitvalAddEarlyPendigList: "/fastival/early-pending-approvals",
    fasitvalAddHistory: "/fastival-history",
    fasitvalAddListEmp: "/emp-fastival/list",
    applyFasitvalAdd: "/apply-fastival-advance",
    festivalAdvanceEmpForRM: "/festival-advance/list-repMan",
    festivalAdvanceEmpForRMApprove: "/festival-advance/list-repMan/approve/:id",
    leaveDashboard: "/leave",
    leaveList: "/leaves/list",
    pendingApprovalsList: "/leaves/pending-approvals",
    leaveHistory: "/leave-history",
    leavesListEmp: "/emp-leaves/:code",
    applyLeave: "/apply-leave",
    leaveBulkUpload: "/leave/bulk-upload",

    creditLeave: "/leave/creditLeave",
    creditPeriodicLeave: "/leave/creditPeriodicLeave",

    leaveTypeList: "/settings/leave-type",
    addLeaveType: "/settings/leave-type/add",
    editLeaveType: "/settings/leave-type/edit/:code",

    attendanceTypeList: "/settings/attendance-type",
    addattendanceType: "/settings/attendance-type/add",
    editattendanceType: "/settings/attendance-type/edit/:code",

    loanTypeList: "/settings/loan-type",
    addLoanType: "/settings/loan-type/add",
    editLoanType: "/settings/loan-type/edit/:code",

    loanList: "/loan/list",
    loanHistory: "/inactive",
    editLoan: "/loan/:code",
    editLoanEmp: "/loan-emp/:code",
    addLoan: "/add-loan",

    holidayTypeList: "/settings/holiday-type",
    addHolidayType: "/settings/holiday-type/add",
    editHolidayType: "/settings/holiday-type/edit/:code",
    // holidayTypes: '/settings/holiday-types',
    //     addHolidayTypes: '/settings/holiday-types/add',
    //     editHolidayTypes: '/settings/holiday-types/edit/:code',

    compOffList: "/comp-offs",
    compOffHistory: "/comp-off-history",
    compOffListEmp: "/comp-offs/:code",
    applyCompOff: "/apply-comp-off",
    wfhHistory: "/wfh-history",
    wfhList: "/wfh-list",
    wfhListEmp: "/wfh-list/:code",
    applyWFH: "/apply-wfh",
    odList: "/od-list",
    odHistory: "/od-history",
    odListEmp: "/od-list/:code",
    applyod: "/apply-od",
    salaryList: "/salary",
    paydayList: "/paiddays",
    settings: "/settings",

    // uploadEmployee: '/upload-employee',
    uploadEmployeeStep2: "/upload-employee-step2",
    helpdesk: "/helpdesk",
    helpdeskTimeline: "/helpdesk/timeline/:code",
    increment: {
      basic: "/increment/basics/list",
      basicAdd: "/increment/basics/Add",
      pqp: "/increment/pqp/list",
      pqpAdd: "/increment/pqp/Add",
      sppay: "/increment/sppay/list",
      sppayAdd: "/increment/sppay/Add",
    },
    settingsOption: {
      updateReportingManager: "/settings/assign-new-rep-man/edit",
      reportingManagerConfig: "/settings/rep-man-config",
      addReportingManagerApproval: "/settings/rep-man-config/add",
      editReportingManagerApproval: "/settings/rep-man-config/edit/:id",
      componentSalaryLists: "/settings/salaryComponents",
      salaryAddComponent: "/settings/add-component",
      addGeofencing: "/settings/add-geofencing",
      geofencing: "/settings/list-geofencing",
      editGeofencing: "/settings/geofencing/:code",
      user: "/settings/user",
      department: "/setting/department",
      addDepartment: "/setting/add-department",
      editDepartment: "/setting/edit-department",
      role: "/settings/role",
      addRole: "/settings/add-role",
      editRole: "/settings/edit/role",
      permission: "/settings/permission",
      locationList: "/settings/region",
      addLocation: "/settings/region/add",
      editLocation: "/settings/region/:code",
      designation: "/setting/designation",
      addDesignation: "/setting/add-designation",
      editDesignation: "/setting/edit-designation",
      shifts: "/settings/shifts",

      // perquisites configration
      fuelList: "/settings/perquisites/fuel",
      addFuel: "/settings/perquisites/fuel/add",

      tadaList: "/settings/perquisites/tada",
      addtada: "/settings/perquisites/tada/add",
      editTada: "/settings/perquisites/tada/edit/:id",

      hotelList: "/settings/perquisites/hotel",
      addHotel: "/settings/perquisites/hotel/add",
      editHotel: "/settings/perquisites/hotel/edit/:id",

      newPaperList: "/settings/perquisites/news-paper",
      addNewsPaper: "/settings/perquisites/news-paper/add",
      editNewsPaper: "/settings/perquisites/news-paper/edit/:id",

      briefCaseList: "/settings/perquisites/brief-case",
      addBriefCase: "/settings/perquisites/brief-case/add",
      editBriefCase: "/settings/perquisites/brief-case/edit/:id",

      entertainmentList: "/settings/perquisites/entertainment",
      addEntertainment: "/settings/perquisites/entertainment/add",
      editEntertainment: "/settings/perquisites/entertainment/edit/:id",

      uniformAndLiveriesList: "/settings/perquisites/uniform-and-liveries",
      addUniformAndLiveries: "/settings/perquisites/uniform-and-liveries/add",
      editUniformAndLiveries:
        "/settings/perquisites/uniformAndLiveries/edit/:id",

      leaveApprovalList: "/settings/leave/leave-Approval-List",
      addLeaveApproval: "/settings/leaves/leave-Approval-List/add",
      editLeaveApproval: "/settings/leaves/leave-Approval-List/edit/:id",

      paymentApprovalList: "/settings/payment/payment-Approval-List",
      addPaymentApproval: "/settings/payment/payment-Approval-List/add",
      editPaymentApproval: "/settings/payment/payment-Approval-List/edit/:id",

      perquisiteApprovalList: "/settings/perquisites/perquisite-Approval-List",
      addPerquisiteApproval:
        "/settings/perquisites/perquisite-Approval-List/add",
      editPerquisiteApproval:
        "/settings/perquisites/perquisite-Approval-List/edit/:id",

      MobileList: "/settings/perquisites/mobile",
      addMobile: "/settings/perquisites/mobile/add",
      editMobile: "/settings/perquisites/mobile/edit/:id",

      medicalList: "/settings/perquisites/medical",
      addMedical: "/settings/perquisites/medical/add",
      editMedical: "/settings/perquisites/medical/edit/:id",

      // leave: '/settings/leave',
      // addLeave: '/settings/leave/add',
      // editLeave: '/settings/leave/edit/:code',

      // holidayTypes: '/settings/holiday-types',
      // addHolidayTypes: '/settings/holiday-types/add',
      // editHolidayTypes: '/settings/holiday-types/edit/:code',

      document: "/settings/document",
      addDocument: "/settings/document/add",
      editDocument: "/settings/document/edit/:code",
      salaryComponentList: "/settings/salary-component",
      addSalaryComponent: "/settings/salary-component/add",
      editSalaryComponent: "/settings/salary-component/:code",
      salaryDeductionList: "/settings/salary-deduction",
      addSalaryDeduction: "/settings/salary-deduction/add/:type",
      editSalaryDeduction: "/settings/salary-deduction/edit",
      salaryAllowanceList: "/settings/salary-allowance",
      addSalaryAllowance: "/settings/salary-allowance/add/:type",
      editSalaryAllowance: "/settings/salary-allowance/edit",
      salaryProfileMemberList: "/settings/salary-profile-member",
      addSalaryProfileMember: "/settings/salary-profile-member/add",
      editSalaryProfileMember: "/settings/salary-profile-member/:code",
      salaryProfileList: "/settings/salary-profile",
      addSalaryProfile: "/settings/salary-profile/add",
      editSalaryProfile: "/settings/salary-profile/:code",
      companyBranchList: "/settings/company-branch-list",
      bulkUploadCompanyBranch: "/settings/bulk-upload-branch",
      addCompanyBranch: "/settings/add-company-branch",
      editCompanyBranch: "/settings/edit-company-branch/:code",
      companyBranchCalender: "/settings/company-branch-calender",
      companyDetail: "/settings/company-detail",
      employeeProfile: "/settings/employee-profile",
      userList: "/settings/user-list",
      addUser: "/settings/add-user",
      edituser: "/settings/edit-user",
      helpdeskListCategory: "/setting/helpdesk/list-category",
      helpdeskAddCategory: "/setting/helpdesk/add-category",
      helpdeskEditCategory: "/setting/helpdesk/edit-category",
      helpdeskAddSubCategory: "/setting/helpdesk/add-sub-category",

      addBranchCategory: "/settings/branch-categories/add",
      branchCategoryList: "/settings/branch-categories",
      editBranchCategory: "/settings/branch-categories/:id",

      AddPensionRule: "/settings/pension-rule/add",
      pensionRuleList: "/settings/pension-rule",
      editPensionRule: "/settings/pension-rule/:id",
    },
    payrollCycleList: "/payroll",
    payrollCycleEmployeeList: "/payroll/employee-list",
    salarySlip: "/payroll/salary-slip",

    assetLiabilityAdd: "/asset-liability/add",
    assetLiabilityList: "/asset-liability/list",
    assetLiabilityListAdmin: "/asset-liability/complete-list",
    addImmovable: "/asset-liability/add-immovable",
    addMovable: "/asset-liability/add-movable",
    addDebit: "/asset-liability/add-debit",
    addShare: "/asset-liability/add-share",
    assetDeclaration: "/asset-liability/add-declaration",
    editAssetDetailForm: "/asset-liability/detail-form/:id",
    editAssetImmovable: "/asset-liability/immovable-form/:id",
    editAssetMovable: "/asset-liability/movable-form/:id",
    editAssetDebt: "/asset-liability/debt-form/:id",
    editAssetShare: "/asset-liability/share-form/:id",
    editAssetDeclaration: "/asset-liability/declaration-form/:id",

    incrementAdd: "/increment/add",
    incrementList: "/increment/list",

    pensionRun: "/pension-superannuation",
    pensionDetail: "/pension-superannuation/employee-list",
    pensionSlip: "/pension-superannuation/pension-slip",
    pensioneEmpList: "/pension-superannuation/employee/list",
    pensionConfig: "/pension-superannuation/configuration",
    addPensionAllowance: "/pension-superannuation/pension-allowance/add/:type",
    editPensionAllowance: "/pension-superannuation/pension-allowance/edit",
    medicalCertificate: "/leaveSupportingDocs/",

    addPensionRule: "/pension-superannuation/config/pension-rule/add",
    editPensionRule: "/pension-superannuation/config/pension-rule/:id",
    addCommutataionFactor: "/pension-superannuation/config/factor/add",
    editCommutataionFactor: "/pension-superannuation/config/factor/:id",
  },
  title: {
    locationList: "Location list - HRMS",
    addLocation: "Add location - HRMS",
    editLocation: "Edit location - HRMS",
  },
  cookie: {
    token: "tk.hrms.com",
    userDetail: "ud.hrms.com",
    locale: "lo.hrms.com",
    authentication: "auth.hrms.com",
  },
  storage: {
    language: "lg.hrms.com",
    locale: "lo.hrms.com",
  },
};
